from turtle import *
color('red')
while True:
    speed(1)
    shape("turtle")
    write("Chicken, Fox, Grain")
    forward(150)
    write("chicken")
    forward(150)
    write("Chicken")
    right(10)
    backward(150)
    write("Alone")
    backward(150)
    write("Fox, Grain")
    left(10)
    forward(150)
    write("Grain")
    forward(150)
    write("Grain, Chicken")
    right(10)
    backward(150)
    write("Chicken")    
    backward(150)
    write("Chicken, Fox")
    left(10)
    forward(150)
    write("Fox")
    forward(150)
    write("Fox, Grain")  
    right(10)
    backward(150)
    write("Alone")
    backward(150)
    write("Chicken")
    left(10)
    forward(150)
    write("Chicken")
    forward(150)
    write("Chicken, Fox, Grain")
    break
end_fill()
done()